### ISSUE TITLE
Hotbar Message Disabled

### ISSUE THREAD

**Issue by EllairaX** [ZombieStriker/PluginConstructorAPI#3]
```
29.07 18:44:24 [Server] WARN [PluginConstructorAPI] HotBarMessager disabled! Something went wrong with: sendHotBarMessage
29.07 18:44:24 [Server] WARN [PluginConstructorAPI] Report this to Zombie_Striker
29.07 18:44:24 [Server] WARN [PluginConstructorAPI] Needed Information: Paper, git-Paper-127 (MC: 1.16.1), 1.16.1-R0.1-SNAPSHOT
29.07 18:44:24 [Server] WARN [PluginConstructorAPI] https://github.com/ZombieStriker/PluginConstructorAPI
```

**Comment by mcdaddytalk** [comment]
Same:

```
13.02 14:49:53 [Server] WARN [mcMMOHorse] Loaded class me.zombie_striker.pluginconstructor.HotbarMessager from PluginConstructorAPI v1.0.52 which is not a depend, softdepend or loadbefore of this plugin.
13.02 14:49:53 [Server] WARN java.lang.NoSuchMethodException: net.minecraft.server.v1_16_R3.PacketPlayOutChat.<init>(net.minecraft.server.v1_16_R3.IChatBaseComponent, byte)
13.02 14:49:53 [Server] WARN at java.base/java.lang.Class.getConstructor0(Class.java:3349)
13.02 14:49:53 [Server] WARN at java.base/java.lang.Class.getConstructor(Class.java:2151)
13.02 14:49:53 [Server] WARN at me.zombie_striker.pluginconstructor.HotbarMessager.<clinit>(HotbarMessager.java:49)
13.02 14:49:53 [Server] WARN at com.blueskullgames.horserpg.skills.Skill.addXP(Skill.java:66)
13.02 14:49:53 [Server] WARN at com.blueskullgames.horserpg.listeners.HorseListener.onEntityDamage(HorseListener.java:130)
......
[Sat, 13. Feb 2021 14:49:53 UTC WARN] [PluginConstructorAPI] HotBarMessager disabled! Something went wrong with: sendHotBarMessage
[Sat, 13. Feb 2021 14:49:53 UTC WARN] [PluginConstructorAPI] Report this to Zombie_Striker
[Sat, 13. Feb 2021 14:49:53 UTC WARN] [PluginConstructorAPI] Needed Information: Paper, git-Paper-457 (MC: 1.16.5), 1.16.5-R0.1-SNAPSHOT
[Sat, 13. Feb 2021 14:49:53 UTC WARN] [PluginConstructorAPI] https://github.com/ZombieStriker/PluginConstructorAPI
```

**Comment by Grievous07** [comment]
same

28.02 14:32:54 [Server] WARN [PluginConstructorAPI] HotBarMessager disabled! Something went wrong with: sendHotBarMessage
28.02 14:32:54 [Server] WARN [PluginConstructorAPI] Report this to Zombie_Striker
28.02 14:32:54 [Server] WARN [PluginConstructorAPI] Needed Information: Paper, git-Paper-"3dadd97bb" (MC: 1.16.5), 1.16.5-R0.1-SNAPSHOT
28.02 14:32:54 [Server] WARN [PluginConstructorAPI] https://github.com/ZombieStriker/PluginConstructorAPI
28.02 14:32:55 [Server] WARN [PluginConstructorAPI] HotBarMessager disabled! Something went wrong with: sendHotBarMessage
28.02 14:32:55 [Server] WARN [PluginConstructorAPI] Report this to Zombie_Striker
28.02 14:32:55 [Server] WARN [PluginConstructorAPI] Needed Information: Paper, git-Paper-"3dadd97bb" (MC: 1.16.5), 1.16.5-R0.1-SNAPSHOT
28.02 14:32:55 [Server] WARN [PluginConstructorAPI] https://github.com/ZombieStriker/PluginConstructorAPI
28.02 14:32:57 [Server] WARN [PluginConstructorAPI] HotBarMessager disabled! Something went wrong with: sendHotBarMessage
28.02 14:32:57 [Server] WARN [PluginConstructorAPI] Report this to Zombie_Striker
28.02 14:32:57 [Server] WARN [PluginConstructorAPI] Needed Information: Paper, git-Paper-"3dadd97bb" (MC: 1.16.5), 1.16.5-R0.1-SNAPSHOT
28.02 14:32:57 [Server] WARN [PluginConstructorAPI] https://github.com/ZombieStriker/PluginConstructorAPI
