### ISSUE TITLE
v1.1.53 spawns infinite (?) threads after 15 to 20 minutes

### ISSUE THREAD

**Issue by kccricket** [ZombieStriker/PluginConstructorAPI#6]
Approximately 15 or 20 minutes after server start, PluginConstructorAPI begins spawning a seemingly infinite number of threads.

https://spark.lucko.me/LYpLBG5ctt

Reproducible on Paper 1.20.1 build 196, Java 17, Linux or Windows.

PluginConstructorAPI and Spark profiler are the only two plugins installed.

**Comment by SissioMisio** [comment]
Same problem!
Purpur 1.20.2

**Comment by rubenbarkman** [comment]
Same problem here - managed to narrow it down to a fresh Purpur #2082 1.20.2 install with just PluginConstructorAPI.

After 10-15 minutes the issue starts.

**Comment by Hiroyugane** [comment]
Can confirm - 1.0.52 works, 1.0.53 lets 24 cpu-cores run on 100% after ~5-10 Minutes.

Paper 1.20.4 #196

**Comment by ZombieStriker** [comment]
Please delete PluginConstructorAPI. It serves no purpose at this point, and is not maintained.

**Comment by rubenbarkman** [comment]
> Please delete PluginConstructorAPI. It serves no purpose at this point, and is not maintained.

In that case, I would strongly recommend to archive this repo. This way at least people know
